apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crypto-tracker
  template:
    metadata:
      labels:
        app: crypto-tracker
    spec:
      containers:
        - name: crypto-tracker
          image: nirmal258035/crypto_tracker:01
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: crypto-tracker-service
spec:
  selector:
    app: crypto-tracker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
